version: '3.8'

services:
  # Base de Datos
  mongodb:
    image: mongo:latest
    container_name: farm-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persistencia de datos

  # API Backend
  backend:
    build: ./backend
    container_name: cups_back
    ports:
      - "8000:8000"
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    depends_on:
      - mongodb

  # Aplicación Frontend
  frontend:
    build: ./frontend
    container_name: cups_front
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  mongo-data: